#!/bin/bash

# Author: Chris Humphreys
# Date: 08/29/19
# File: svtopng
# Description: simple little script that compiles all graphviz source files in 
# the current directory and builds them into .png files
# Requirements: must have graphviz installed.

build_pngs_from_sv() {
	for i in *.gv; do
		dot -Tpng $i -o ${i%gv}png;
		if [[ $? == 0 ]]; then
			echo -e "\t${i%gv}png built successfully";
		fi;
	done
}

if [[ $# == 1 ]]; then
	dot -Tpng $1 -o ${1%gv}png;
else 
	echo "Usage: gvtopng <graphviz_file>";
fi;
